version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html
      - ./admin:/var/www/admin
      - ./includes:/var/www/includes

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_root_mysql_retrogamesite
      MYSQL_USER: user_retrogamesite
      MYSQL_PASSWORD: pwd_retrogamesite
      MYSQL_ROOT_PASSWORD: root_mysql_retrogamesite
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
volumes:
  mysqldata:
